apiVersion: apps/v1
kind: Deployment
metadata:
  name: prefect-agent-creditcard
  namespace: mlops-prefect
  labels:
    app: prefect-agent
spec:
  selector:
    matchLabels:
      app: prefect-agent
  replicas: 1
  template:
    metadata:
      labels:
        app: prefect-agent
    spec:
      containers:
        - name: agent
          image: ghcr.io/khaosresearch/prefect-creditcard:latest
          command: ["prefect", "agent", "start", "-q", "creditcard"]
          imagePullPolicy: "Always"
          resources:
            limits:
              cpu: "0.1"
              memory: "500Mi"
            requests:
              cpu: "0.1"
              memory: "500Mi"
          env:
            - name: PREFECT_API_URL
              value: http://192.168.219.71:32000/api
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prefect-agent
  namespace: mlops-prefect
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/status"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prefect-agent-role-binding
  namespace: mlops-prefect
subjects:
  - kind: ServiceAccount
    name: default
    namespace: mlops-prefect
roleRef:
  kind: Role
  name: prefect-agent
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prefect-agent
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prefect-agent-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: mlops-prefect
roleRef:
  kind: ClusterRole
  name: prefect-agent
  apiGroup: rbac.authorization.k8s.io

